---
name: lab-03
break: true
indent: 4
---

src/main/java/labthree:
    DisplayPotion.java:
        ConfirmFileExists
        CountSingleLineComments --language Java --count 4
        MatchFileFragment --fragment "distilled water" --count 1 --exact
        MatchFileFragment --fragment "mashed beetle" --count 1 --exact
        MatchFileFragment --fragment "TODO" --count 0 --exact
        MatchFileFragment --fragment "\t" --count 6
        MatchFileFragment --fragment "String " --count 4 --exact
        MatchFileFragment --fragment "int yieldAmt = 1;" --count 1 --exact
        MatchFileFragment --fragment "{Your Name Here}" --count 0 --exact
        MatchFileFragment --fragment "double bindingAmt = 1.0;" --count 1 --exact
        MatchFileFragment --fragment "double liquidAmt = 4.2;" --count 1 --exact
        MatchFileFragment --fragment "double materialAmt = 3.1;" --count 1 --exact
        MatchFileFragment --fragment "crushed alligator plant" --count 1 --exact

writing:
    reflection.md:
        ConfirmFileExists
        mdl --rules ~MD009,~MD013,~MD0022,~MD026
        CountFileWords --count 250
        CountFileParagraphs --count 4
        MatchFileFragment --fragment "TODO" --count 0 --exact
        MatchFileFragment --fragment "{YOUR NAME HERE}" --count 0 --exact
        
CountCommits --count 3
ExecuteCommand --command "gradle build"
CountCommandOutput --command "gradle -q --console plain run" --count 5